from add_dots import *
from add_ink_leak import *
from add_shadow_final import *
from add_watermark import *
from bg_extraction import *
from color_extraction import *
from contains_gray import *
from elastic_transform import *
from general_quality_reduce import *
from half_paper import *
from ink_leak_final import *
from ink_reduce import *
from make_it_old_final import *
from overlap_final import *
from perspective_transform import *
from random_break_reduce import *
from rotate import *
from scanned import *
from seperate_binary import *
from seperate_lines import *
from texture_overlap import *
from warp_texture_blur_sticker import *